### ISSUE TITLE
Ship operating system specific webfonts

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#17]
To work around the webfont issue we need to ship different font files depending on the operating system of the user.

I think it would be best to decide upon the operating system using the user agent string in the HTTP header and link one of two `font.css` files in the `<head>` of the homepage. But I’m open for other approaches. Effectively we need to switch the paths in the `@font-face` rules between Mac/Linux and Windows.

Maybe there’s also a way to configure the webfontloader to load the correct font files directly.

I added two sets of webfont files and linked an additional entry point `fonts-mac.css` in `home.html` for now.

**Comment by fcheslack** [comment]
Is Windows the only outlier, or is there any special behavior needed for iOS or Android?

**Comment by flachware** [comment]
Windows is the only outlier (iOS definitely not and I just tested on Android, looks good to me with the Mac version).
