### ISSUE TITLE
Home page screenshot tweaks

### ISSUE THREAD

**Issue by dstillman** [zotero/web-components#26]
- [x] No Notes column
- [x] Add some groups
- [x] Standard traffic lights instead of monochrome macOS window controls
- [x] en-US `10/13/2017, 9:47:14 AM` dates (m-d-y, 12-hour time with no leading zero) for Date Added/Date Modified
- [x] Create high-res thesis icon

**Comment by flachware** [comment]
@stakats mentioned once that the notes column is an import feature to him – still remove?

**Comment by dstillman** [comment]
I dunno — I just think it's kind of ugly (and it's not on by default). But showing notes (and PDFs) in some way is important, so what if we just show an item open with multiple notes and a PDF?

**Comment by dstillman** [comment]
I nominate @stakats to write some smart things about Last Action Hero.
