### ISSUE TITLE
Show username in menu when logged in

### ISSUE THREAD

**Issue by dstillman** [zotero/web-components#33]
On the new homepage, if you're logged in you see My Profile, Inbox, and the like in the menu, but you don't see your username anywhere like you do on the desktop. We should at least show that in the menu.

(It might also be nice to do what many sites do and show a miniature version of your profile icon to the left of the hamburger menu when logged in that would take you to your profile or account settings.)

**Comment by flachware** [comment]
I replaced 'My Profile' with the user name in the mobile menu, that’s what e.g. GitHub does. Once we have user icons we can consider showing it instead of / additionally to the user name.
