### ISSUE TITLE
Zotero logo rendering quality

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#34]
The rendering quality of the Zotero logo in Chrome is worse than it could be. It is probably a Chrome bug and related to this one: https://bugs.chromium.org/p/chromium/issues/detail?id=710293

The bug occurs when a certain threshold of total SVG file size is exceeded. The comparisons below show the logo rendered on the homepage ('jagged') vs the logo rendered alone in a new browser tab ('smooth').

Logo 1x jagged:
![zotero-logo-jagged 1x](https://user-images.githubusercontent.com/419747/37209983-5dbbfece-23a7-11e8-8dc7-f69db5b41a2f.png)

Logo 1x smooth:
![zotero-logo-smooth 1x](https://user-images.githubusercontent.com/419747/37209989-5f8396b8-23a7-11e8-8295-8a2efb591b43.png)

Logo 2x jagged:
![zotoer-logo-jagged 2x](https://user-images.githubusercontent.com/419747/37209994-61f3c0e4-23a7-11e8-94db-2d3165d2c84f.png)

Logo 2x smooth:
![zotero-logo-smooth 2x](https://user-images.githubusercontent.com/419747/37209997-62e2024a-23a7-11e8-8f9a-54667e8fc795.png)

**Comment by flachware** [comment]
@dstillman @tnajdek can anybody reproduce the jagged logo version on the homepage with either hardware acceleration on or off?

I can reproduce it consistently with hardware acceleration turned on, but as I am experiencing so many issues with Chrome and hardware acceleration I’d close this issue if nobody else sees this.

**Comment by tnajdek** [comment]
I tried couple of configurations (acceleration on/off, 1x/2x pixel density, integrated/discrete gpu) and I don't seem to get the jagged one ever.

**Comment by flachware** [comment]
Alright, thanks.
