### ISSUE TITLE
Enhance form loading

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#36]
@fcheslack I realized that there is an animation that reveals the form on the start page. Why does it take a little longer to load the form than the other components, is this about the Captcha?

The animation changes to scrollbar size obviously, which lets the page look a little unstable after most parts have already been rendered. I think we know exactly the height of the form, how about adding a min-height to the form and perhaps show a spinner if the form takes more than say one or two seconds to load? Setting a min-height wouldn’t be very flexible, but e.g. in case the Captach size would change we should have a look at the layout anyway, so it might be an acceptable solution in this case.

**Comment by flachware** [comment]
~~Maybe relevant in the context of the form loading and min-height: in the bootstrap4 branch we show the `.username-message` by default ('Your email address can be used to log in to your Zotero account, but not as your username.'), but in the published version we do not.~~

~~If we decide to set a min-height instead of the initial animation, could you update the bootstrap4 branch to reflect the published version more closeley (do not show the `.username-message` by default, that is)?~~

I just realized that the `.username-message` isn’t shown by default but the username field is prefilled with `zotero@zotero.org`.

**Comment by fcheslack** [comment]
I think this was more a side-effect of being in a <VerticalExpandable>, which ran the animation on mount intentionally in other contexts. It's now using a bootstrap4 Collapse, which doesn't have the same behaviour. The captcha does still take slightly longer to load causing a small amount of re-flow, so we may still want a min-height inside the Collapse.

**Comment by flachware** [comment]
The registration form looks fine to me now (no clipped form control focus, no initial animation). I’ll add a min-height to the Captcha, that should stabilize the loading of the form.
