### ISSUE TITLE
Consider using reactstrap collapse component

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#37]
@fcheslack I can still reproduce a the little hickup in the _all-extension_ transition, how about using the reactstrap collapse component (https://reactstrap.github.io/components/collapse/)? we already use one or two reactstrap components in ZoteroBib, but for the web-components it might make even more sense to use those components wherever possible as we actually use Bootstrap here.

**Comment by fcheslack** [comment]
Alright. This is now using Collapse meaning all the rest of reactstrap is available. Taking advantage of it seems to generally make sense to me. My only question then is whether using it even for things like <Button> makes sense to you for additional styling (taking into consideration that not everything will be in React components so sometimes we'll be adding the normal bootstrap classes to html anyway).

**Comment by flachware** [comment]
Reactstrap looks good to me in the registration form – you still need to add it to `#all-extensions` in the first section (because there we have the hickup in the animation).

As far as I know the reactstrap components can be pulled in component by component (I think we do it that way in ZoteroBib), so if that makes more sense to you, there is no need to have all reactstrap components in the project.

I fear I can’t follow your last sentence, I think there is missing a part between 'for things like … makes sense to you'. What are your concerns regarding reactstrap and styling?

**Comment by fcheslack** [comment]
I just meant for your ease of styling because it means potentially different markup when editing (even though it results in the same markup in the browser). It's probably not something to be concerned about so we can pull in and use reactstrap components whenever it seems convenient/cleaner.
