### ISSUE TITLE
Show spinner while register form is processing

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#39]

**Comment by flachware** [comment]
@fcheslack I think we should show a spinner in the _Register_ button while the form is processing. I added the 'inline-feedback' markup we use in ZoteroBib to the button. It basically works like that: the default text is used to stretch the button/parent (in this specific case we have a block button, so it doesn’t get stretched) and the 'feedback' is only visible when needed and does not take up any space. The two elements in the `.inline-feedback` element get switched by setting an `.active` class on the `.inline-feedback` element. I also think we should disable the button by adding a `disabled attribute` on the button.

So I would need your help with two things here: when the register form is processing, the `disabled` attribute should be set on the _Register_ button and the `.active` class should be set on the `.inline-feedback` element inside.

**Comment by fcheslack** [comment]
Is the off-center spinner intentional? I don't think I did anything to change that.

**Comment by flachware** [comment]
Good catch! For some reason a required class didn’t make it into my commit.
