### ISSUE TITLE
Add validation state to form controls

### ISSUE THREAD

**Issue by flachware** [zotero/web-components#40]
@fcheslack now that we use Bootstrap we can make use of their validation styles: https://getbootstrap.com/docs/4.1/components/forms/#how-it-works. Instead of just showing a red/green text below a control we can also apply the color to control’s border and box-shadow.

If I understand correctly their `.was-validated :valid/:invalide` approach does only work for the entire form, but we validate each field directly after input – so we’d have to use their `.is-valid` and `.is-invalid` classes on `.form-control`. There are also form components in reactstrap, but I don’t know if they are helpful in our case.

Once we have those classes we can also use them to handle the visibility of the error messages below the controls.

**Comment by fcheslack** [comment]
In my experience the built in browser form validation has a lot of issues, so I suspect we'll generally stick with the manual ones, but I've updated the register form to use the bootstrap classes.
One caveat is that I think it requires the feedback text to be a sibling of the input, which may interfere with styles for something like input-group.

**Comment by flachware** [comment]
Yes I believe the built-in validation in browsers couldn’t do that kind of sophisticated checks that we do?

Good that you mention the input-group feedback text combination – but it looks good to me. Be aware that Bootstrap uses the subsequent sibling combinator (`~`) and not the next sibling combinator (`+`). So yes, the feedback text needs to be a sibling of the form-control, but not a _direct_ sibling, which should be fine, even with input groups, as the feedback text is inside the input group (like in the Bootstrap docs).
