### ISSUE TITLE
Make PDFs easier to click on [Feature Request]

### ISSUE THREAD

**Issue by tylerferrara** [zotero/web-components#53]
### Feature Request
Add `cursor: pointer` to PDF component

#### Background
I'm an avid user of Zotero and notice it's quite hard to click the PDF documents attached within the web library. Consider adding the styles `cursor: pointer` for the PDF component and possibly making it larger. It sometimes takes me three taps on a tablet just to open the documents.

**Comment by tnajdek** [comment]
Thank you for reporting the issue, in future please use [Zotero Forums](https://forums.zotero.org/) for bugs and feature requests.

Not sure if this is what you mean but I can confirm that there is something odd going on with opening attachments on iOS Safari both from the list (using an icon) and from the attachment details view (clicking on a filename). We will investigate, I've opened an issue in correct repo: zotero/web-library#452

If this is not the issue you're seeing, please let us know (in Zotero Forums) with few more details (which browser, what OS, is it touch or mouse-based interface, what are the steps to reproduce, what you expect to happen and what is actually happening)

**Comment by tnajdek** [comment]
@tylerferrara a new version of Web Library have been deployed where, hopefully, this problem has been resolved.
